name: Deploy Origin API

on:
  workflow_dispatch:
  
  push:
    branches:
      - main
    paths:
      - 'origin/**'
      - '.github/workflows/origin-deploy.yml'

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker Image
        run: |
          docker build \
            -t origin-api:latest \
            ./origin

      - name: Tag Docker Image
        run: |
          docker tag origin-api:latest \
          ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/origin-api:latest

      - name: Push Docker Image
        run: |
          docker push \
          ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/origin-api:latest

      - name: Deploy ECS Service
        run: |
          aws ecs update-service \
            --cluster cdn \
            --service origin-api-service \
            --force-new-deployment
